import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='pt-3 text-center text-6xl'>
        Kaizen App
      </div>

      <li className='mt-8 list-none text-center text-2xl'>
        <Link href="/Resister">Resister</Link>
      </li>
    </div>
  )
}
