import Head from 'next/head';
import { useForm } from 'react-hook-form';
import Kaizen from '../types/IKaizen';

export default function Resister() {
  const form = useForm<Kaizen>();
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
