import { Prisma } from '@prisma/client';
import Head from 'next/head';
import Form from '../components/Form';
import EventHandler from '../types/EventHandler';
import IKaizen from '../types/IKaizen';

type RegisterProps = {
  formState: IKaizen,
  onSubmit: EventHandler<IKaizen>,
}

const Resister: React.FC<RegisterProps> = ({
  formState,
  onSubmit,
}) => {
  async function saveKaizen(kaizen: any) {
    const response = await fetch('/api/createKaizen', {
      method: 'POST',
      body: JSON.stringify(kaizen)
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }
    return await response.json();
  }

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form
        formState={formState}
        onSubmit={(data) => saveKaizen(data)}
      />
    </div>
  )
}

export default Resister;
