import { Prisma } from '@prisma/client';
import Head from 'next/head';
import Form from '../components/Form';
import EventHandler from '../types/EventHandler';
import IKaizen from '../types/IKaizen';

const Resister: React.FC = () => {

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </div>
  )
}

export default Resister;
